### ISSUE TITLE
getting data

### ISSUE THREAD

**Issue by uurcelikk** [HUANGLIZI/C2FVL#2]
def read_attr(filename):
    df = pd.read_excel(filename)
    bt = {}
    num={}
    lu={}
    lm={}
    ll={}
    ru={}
    rm={}
    rl={}
    for i in df.index.values:  # Gets the index of the row number and traverses it
        bt[df.Image[i]]= df.bilateral[i]
        num[df.Image[i]] = df.number[i]
        lu[df.Image[i]]= df.lupper[i]
        lm[df.Image[i]] = df.lmiddle[i]
        ll[df.Image[i]]= df.llower[i]
        ru[df.Image[i]] = df.rupper[i]
        rm[df.Image[i]]= df.rmiddle[i]
        rl[df.Image[i]] = df.rlower[i]
    return bt,num,lu,lm,ll,ru,rm,rl  # return dict (key: values)
    
    How can i change this part. Because itis giving error that AttributeError: 'DataFrame' object has no attribute 'bilateral' 
    
    Thank you.

**Comment by HUANGLIZI** [comment]
You need to download the text annotation first. And it has the "bilateral" column.

**Comment by uurcelikk** [comment]
Hi, 
Congrats for your that work.

I was working with MosMedData+.  Thank you for your reply.

**Comment by uurcelikk** [comment]
If it is ready, Can i get text annotation of MosMedData+?

**Comment by JackHeroFly** [comment]
> You need to download the text annotation first. And it has the "bilateral" column.
你好，在您这个C2FVL仓库总中并未找到“The text annotation of MosMedData+ dataset“，在您LViT仓库中找到了，但是运行训练代码，报出错误“'DataFrame' object has no attribute 'bilateral'”，您方便发送一份有 "bilateral" column的text annotation吗？非常感谢，1934024210@qq.com
